export declare const getRandNum: (min: number, max: number, exclude?: number[]) => number;
export declare const getRandBool: (rate?: number) => boolean;
export declare const roundTo: (number: number, decimals?: number) => number;
export declare const floorTo: (number: number, decimals?: number) => number;
export declare const ceilTo: (number: number, decimals?: number) => number;
export declare const countDecimals: (number: number) => number;
export declare const gcd: (a: number, b: number) => number;
export declare const factorial: (number: number) => number;
export declare const avg: (...numbers: number[]) => number;
